### ISSUE TITLE
Some confusion about Training Model

### ISSUE THREAD

**Issue by cb632482135qq** [taigw/brats17#11]
Hello Everyone
      
      I want to train a model for mysef ,so I run the train.py  with 2015 Brats Data.

     However , the result of loss changes from 0.2 to 0.3 randomly.

     Thus, even I am unable to achieve convergence.
  
     So, I am confused that whether this is the reason for imperfectly segmentation.

**Comment by GuojingZhao** [comment]
I have same situation that loss about 0.3 from 500 epoch to 20000 epoch.  Is that normal?
