### ISSUE TITLE
test_all_classes tests only class=2

### ISSUE THREAD

**Issue by faustomilletari** [taigw/brats17#16]
Hello,
I have tried to test using the network but it seems from the config file test_all_classes that actually only class 2 gets predicted. could you tell me how to update that config file to test for class 1,2,3,4? 

Regards,

**Comment by faustomilletari** [comment]
this is the config https://github.com/taigw/brats17/blob/master/config17/test_all_class.txt

**Comment by taigw** [comment]
@faustomilletari  I used three binary networks to segmet these structures. So the class number for each network was 2.
