### ISSUE TITLE
Duplicate entries in train_names_all_lggx3.txt

### ISSUE THREAD

**Issue by fordanic** [taigw/brats17#2]
Is there a reason why the LGG dataset have multiple entries in train_names_all_lggx3.txt.

**Comment by taigw** [comment]
This is because the number of LGG images is much smaller than that of HGG images.

**Comment by siddharthamantrala** [comment]
Is it possible to train without a GPU?

**Comment by siddharthamantrala** [comment]
Do I need to change the directory paths in the Job_test file to test the code with the dataset, even if i dont have a GPU?

**Comment by taigw** [comment]
A GPU is required for training. Otherwise the training process would be very slow.
